name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update rust version
      uses: actions-rs/toolchain@v1
      with: 
        toolchain: stable
        override: true
    - name: Build project
      run: cargo build --verbose

  style:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update rust version
      uses: actions-rs/toolchain@v1
      with: 
        toolchain: stable
        override: true
    - name: Format
      run: cargo fmt -- --check
    - name: Clippy
      run: cargo clippy --verbose

  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update rust version
      uses: actions-rs/toolchain@v1
      with: 
        toolchain: stable
        override: true
    - name: Run tests
      run: cargo test --verbose
